
Currently Loaded Modules:
  1) CUDA/9.0.176   2) cuDNN/7-CUDA-9.0.176   3) anaconda/2021-03-tf2

 

2021-07-13 14:12:06.184951: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-07-13 14:12:08 WARNING  Model 'TurkuNLP/bert-base-finnish-cased-v1' not recognized as an MXNet model; treating as PyTorch model
Some weights of the model checkpoint at TurkuNLP/bert-base-finnish-cased-v1 were not used when initializing BertForMaskedLMOptimized: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLMOptimized from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing BertForMaskedLMOptimized from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
2021-07-13 14:12:15 WARNING  Created scorer of class 'MLMScorerPT'.
2021-07-13 14:12:15 WARNING  Language was set but this model does not use language embeddings!
Traceback (most recent call last):
  File "/home/moisioa3/.local/bin/mlm", line 33, in <module>
    sys.exit(load_entry_point('mlm', 'console_scripts', 'mlm')())
  File "/scratch/work/moisioa3/conv_lm/mlm-scoring/src/mlm/cmds.py", line 184, in main
    args.func(args)
  File "/scratch/work/moisioa3/conv_lm/mlm-scoring/src/mlm/cmds.py", line 235, in cmd_score
    corpus_for_scoring = corpus
UnboundLocalError: local variable 'corpus' referenced before assignment
